namespace: "junipernetworks"
description: "This collection provides modules to interact with Apstra."
name: "apstra"
version: "0.1.3"
readme: "README.md"
authors:
    - "Pratik Dave <pratikd@juniper.net>"
    - "Edwin Jacques <ejacques@juniper.net>"
    - "Nathan Veenker <nveenker@juniper.net>"
license:
    - "MIT"
tags:
    - juniper
    - junipernetworks
    - apstra
    - networking
    - aos
homepage: "https://www.juniper.net/us/en/products/network-automation/apstra.html"
repository: "https://github.com/Juniper/apstra-ansible-collection"
issues: "https://github.com/Juniper/apstra-ansible-collection/issues"