namespace: "juniper"
description: "This collection provides modules to interact with Apstra."
name: "apstra"
version: "1.0.2"
readme: "README.md"
authors:
    - "Pratik Dave <pratikd@juniper.net>"
    - "Edwin Jacques <ejacques@juniper.net>"
license:
    - "Apache License 2.0"
tags:
    - juniper
    - junipernetworks
    - apstra
    - networking
    - aos
homepage: "https://www.juniper.net/us/en/products/network-automation/apstra.html"
repository: "https://github.com/Juniper/apstra-ansible-collection"
issues: "https://github.com/Juniper/apstra-ansible-collection/issues"
build_ignore:
    - antsibull-docs.cfg
    - .apstra-collection
    - conf.py
    - _build
    - .gitignore
